baseURL = 'https://www.laelith.org/'
title = 'Laelith Open Licence'
languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

# Theme
theme = 'laelith'

# Disable kinds we don't need
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap', '404']

# Languages
[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1
    title = 'Laelith Open Licence'
    [languages.en.params]
      description = 'Description and conditions of the Laelith Open Licence'

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = 'home'
      name = 'Home'
      url = '/'
      weight = 1
    [[languages.en.menu.main]]
      identifier = 'licence'
      name = 'Licence'
      url = '/licence'
      weight = 2
    [[languages.en.menu.main]]
      identifier = 'authors'
      name = 'Authors'
      url = '/authors'
      weight = 3
    [[languages.en.menu.main]]
      identifier = 'texts'
      name = 'Texts'
      url = '/texts'
      weight = 4

  [languages.fr]
    languageCode = 'fr'
    languageName = 'Fran√ßais'
    weight = 2
    title = 'Licence Ouverte Laelith'
    [languages.fr.params]
      description = 'Description et conditions de la Licence Ouverte Laelith'
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = 'home'
        name = 'Accueil'
        url = '/fr'
        weight = 1
      [[languages.fr.menu.main]]
        identifier = 'licence'
        name = 'Licence'
        url = '/fr/licence'
        weight = 2
      [[languages.fr.menu.main]]
        identifier = 'authors'
        name = 'Auteurs'
        url = '/fr/authors'
        weight = 3
      [[languages.fr.menu.main]]
        identifier = 'texts'
        name = 'Textes'
        url = '/fr/texts'
        weight = 4

[params]
  author = 'Laelith Foundation'

