# Theme metadata
name = "Laelith"
license = "MIT"
licenselink = "https://github.com/laelith/laelith-theme/blob/main/LICENSE"
description = "Laelith Open Licence"
homepage = "https://www.laelith.org/"
tags = ["bootstrap", "multilingual", "simple"]
features = ["multilingual"]
min_version = "0.100.0"

[author]
  name = "Laelith Foundation"

